### ISSUE TITLE
extra dependency -MUSCLE

### ISSUE THREAD

**Issue by BiologicalScientist** [shimbalama/screen_assembly#3]
Hi, Liking the tool, but have been having a bit of trouble getting the alignment and plotting function working. I'll post separate issues for each thing I have managed to troubleshoot so far. 

In the code you call MUSCLE aligner however this isn't listed as a dependency in the wiki. ClustalO is listed and is called following so I'm not sure if MUSCLE has been removed but is still in the code or should be a listed dependency.

in analysis.py lines 766-792
```python
def versions(args):

    '''
    Save wrapped program version to text
    '''

    with open('versions.txt', 'w') as fout:
        fout.write(str(args)+'\n')
        call(['blastn', '-version'], stdout=fout)
        if args.aln:
            call(['muscle', '-version'], stdout=fout)
        #if args.raxml:
        #    call([args.raxml_executable, '-v'], stdout=fout)
        if args.IQtree:
            call(['iqtree', '-version'], stdout=fout)

def clustal(args, query, seq_type):

    if not os.path.exists(query + '_' + seq_type + '_non_redundant.aln'):
        call(['clustalo',
            '-i', query + '_' + seq_type + '_non_redundant.fasta',
            '-o', query + '_' + seq_type + '_non_redundant.aln',
            '--threads', '1'])#seems faster than just giving clustal muli threads

    if args.plots:
        if seq_type == 'aa':
            gap_plot(args, query, seq_type)
```

**Comment by shimbalama** [comment]
Thanks for that! I can confirm that muscle is no longer used. The line call(['muscle', '-version'], stdout=fout) is just for logging. I'll remove it.
