### ISSUE TITLE
-i option listed in wiki for both INPUT_FOLDER and --percent_identity

### ISSUE THREAD

**Issue by BiologicalScientist** [shimbalama/screen_assembly#4]
Hi,

If using the -i flag for the --percent identity as listed in the wiki it will automatically default to 80 as that flag is already in use for the input folder. Not sure if its an issue in the actual code or not but using --percent_identity instead works.

**Comment by shimbalama** [comment]
Sorry. Typo. -i is input. -pl is percent length and  -pi is percent identity (or --percent_identity). 

Thanks for spotting this!

Liam
