### ISSUE TITLE
name 'iplot' is not defined

### ISSUE THREAD

**Issue by BiologicalScientist** [shimbalama/screen_assembly#5]
Hi, 

When I try the plot function (on MacOSX) I get the following error
```bash
#code run
screen_assembly3.py -t 1 -l 95 --percent_identity 95 -o -k -q genes.mfa -i contigs/
```
Plotting...
Traceback (most recent call last):
  File "/Users/user/.local/bin/screen_assembly3.py", line 232, in <module>
    main()
  File "/Users/user/.local/bin/screen_assembly3.py", line 205, in main
    pool.map(iplot.plot_vars, tmp)
NameError: name 'iplot' is not defined

looking through the script I couldn't see where the module iplot (or plot which is on line 211) is defined (I'm assuming they are calling a module from matplotlib but wasn't sure). Not sure if there is a library that I haven't loaded but it looks like there needs to be a statement importing something as iplot at the beginning of the script. 

```python
        if args.plots:
            print ('Plotting...')
            if args.operon:
                with Pool(processes=int(args.threads)) as pool:
                    tmp = [(args, query, 'nuc') for query in query_seqs]
                    pool.map(iplot.plot_vars, tmp)
            else:
                variant_types(args, assemblies) 
                with Pool(processes=int(args.threads)) as pool:
                    tmp = [(args, query, 'aa') for query in query_seqs]
                    pool.map(plot.plot_vars, tmp)   
            var_pos_csv(args, ana.blast_type)
```

If it helps to troubleshoot it appears some of the plots are working as I get the box_and_carriage plots.svg outputs but I don't get any of the snp/ gap variation plots. Not a major concern but

**Comment by shimbalama** [comment]
Hi. Apologies for not having addressed this sooner. I will look at (all) your issues ASAP.

**Comment by shimbalama** [comment]
This is my favourite bug! I always hit 'i' too many times before editing in vim. Easy fix. Should be done tonight.

Liam

**Comment by BiologicalScientist** [comment]
Thanks for fixing all of the issues! I haven't had a chance to update to the fixed version and run it yet but will let you know how it goes when I do. Just to check should I make sure to git clone the repository to get the newest version or is the pip installer fine as well?

Andrew

**Comment by shimbalama** [comment]
Pip _should_ work (as of right now).  Let me know if you have any issues.
