### ISSUE TITLE
some protein sequences break script "Not making unique seq fasta for BCAL1869_seqs_and_ref_nuc local variable 'i' referenced before assignment"

### ISSUE THREAD

**Issue by BiologicalScientist** [shimbalama/screen_assembly#7]
Hi, I have previously run the script with nucleotide queries which has been working fine however I tried to run with some protein queries and it ran for some but for others I get the following error message 

"Not making unique seq fasta for BCAL1869_seqs_and_ref_nuc local variable 'i' referenced before assignment" 

The issue appears to only effect the sequences that are of concern (the csv and box and carriage plots work for the other queries) and when isolated from the multi fasta into a shorter list the same error occurs. I had a quick dig around and suspect that there might be an indentation/ local variable call issue at line 254 of analysis (if i > 1)  causing the function  responsible for creating the seqs_and_ref_nuc file to throw up the error but not entirely sure.

I am also not sure what it would be that is causing some sequences to fail but others succeed which I assume is a different issue that may be specific to my dataset. In case you want to see if that issue is reproducible here is the link to the sequences I have been using 

https://www.burkholderia.com/downloads/burkholderia/bgd_r_9_1/Burkholderia/complete/fna-complete.tar.gz
(I needed to alter file names to remove # and reduce file name length). 

fasta file is also attached in .txt format.
[mixed_success_fail.txt](https://github.com/shimbalama/screen_assembly/files/5992653/mixed_success_fail.txt)

```
def make_fasta_non_redundant(args, query, seq_type):

    '''
    Boil each multi fasta down to unique seqs for every query - at aa level
    '''
    try:
        redundant_map = collections.defaultdict(list)
        for i, record in enumerate(SeqIO.parse(query + '_seqs_and_ref_' + seq_type + '.fasta','fasta')):
            seq_str = str(record.seq)
            redundant_map[seq_str].append(record.id)


        #write non redundant fasta
        fout= open(query + '_' +seq_type+'_unique_seqs.fasta','w')
        if i > 1:
            for i, seq in enumerate(redundant_map):
                if 'ref' in redundant_map.get(seq):
                    fout.write('>0 ' + ','.join(redundant_map.get(seq))+'\n')
                else:
                    fout.write('>'+ str(i + 1) + ' ' + ','.join(redundant_map.get(seq))+'\n')
                fout.write(seq+'\n')
        fout.close()
    except Exception as e:
        print ('Not making unique seq fasta for',query + '_seqs_and_ref_' + seq_type, e)
```

**Comment by shimbalama** [comment]
Thanks for bring it to my attention. I'll have a look now.

Liam

**Comment by shimbalama** [comment]
I assume you're getting all these errors too?

```
FATAL: FATAL: FATAL: File 'BCAL1869_aa_non_redundant.fasta' contains 1 sequence, nothing to alignFile 'BCAM1669_aa_non_redundant.fasta' contains 1 sequence, nothing to align

File 'BCAS0773_aa_non_redundant.fasta' contains 1 sequence, nothing to align
FATAL: File 'BCAM0996_aa_non_redundant.fasta' contains 1 sequence, nothing to align
```

This looks horrible but it basically just means that there was no hit for the query sequence at that length and seq identity. And  therefore nothing to align and make_fasta_non_redundant throws an error as there's nothing to iterate over. 

I wrote this script years ago and it's now rather embarassing to see how poorly I handled this situation! However, given it's not actually a functional problem I'm not sure I'll find time to tidy it up any time soon I'm afraid. (I now work in a different lab so I have to maintain this code in my own - limited - free time).

Try reducing the stringency of your search if you want to get more hits.

Regards,
Liam

**Comment by BiologicalScientist** [comment]
Thanks for responding so quickly. I fully understand having limited free time and won't be expecting any updates/ fixes for any issues lodged. I'll still post when I encounter anything so that if someone else comes across the same thing there is a record and hopefully a solution if I come across it.  

I had left the -a flag so wasn't getting those error messages but it makes sense that the script will fail to deal with a single hit only. I was expecting there to be at least one hit as I have the reference genome I got the protein sequences from in my database. 

Interestingly when I run the dataset with the same sequences but nucleotides instead of the protein translation I get hits for the genes and protein translations that match for most hits so there is clearly something else at play. I also get several "stops" and some non standard start codons so the issue might be something to do with the codon table/ translation not being standard for burkholderia/ there being too much ambiguity for short protein sequences to accurately screen. could also be my version of tblastN having issues. Don't know enough about how tblastN works behind the scenes but I assume it has to reverse translate to ambiguity codes and then runs blast using that which removes a lot of specificity. I'll stick to using nucleotide sequences for my searches (probably best practice anyway when screening a nucleotide database.) to be on the safe side. 

If you do want to have a look at what might be happening behind the scenes I've attached an example fasta where the protein failed to get a hit but the nucleotide sequence was successful (when run separately). 

Cheers,
Andrew
[BCAS0773_nuc_and_aa.txt](https://github.com/shimbalama/screen_assembly/files/5993185/BCAS0773_nuc_and_aa.txt)

**Comment by BiologicalScientist** [comment]
in case it helps my exact command was 
```
screen_assembly3.py -t 12 -l 80 --percent_identity 50 -a -x -q $sequences -i $directory
```
haven't tried troubleshooting with lowered thresholds as it is working fine with the nucleotide query and don't want to drop specificity too low if I know there should be some high identity hits in the database.

**Comment by shimbalama** [comment]
Thanks Andrew. Definitely good to raise an issue so that if someone else comes across the same thing there is a record. I have come accross similar issues when using protein. 

Have a look at blast_out.txt and see if there are any hits that the script skipped over. If there's some in there try the --keep_flagged parameter. If not, it's a blast issue. Maybe play with blast manually and see if you can get a hit. 

If you think there's some way to improve this script to make it function more acuratelly I'll find time to make that happen. 

Cheers,
Liam
